# Generated by Django 4.1 on 2022-08-27 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.CharField(choices=[('special', '특별한 날'), ('lover', '연인과'), ('company', '회식'), ('family', '가족과'), ('alone', '혼자'), ('activity', '액티비티'), ('friend', '친구와'), ('healing', '힐링')], default='friend', max_length=50)),
                ('location', models.CharField(choices=[('MP', 'mapo'), ('GS', 'gangseo'), ('YC', 'yangcheon'), ('GR', 'guro'), ('YDP', 'yeongdeungpo'), ('GC', 'geumcheon'), ('DJ', 'dongjak'), ('GA', 'gwanak'), ('SC', 'seocho'), ('GN', 'gangnam'), ('SP', 'songpa'), ('GD', 'gangdong'), ('SDM', 'seodaemun'), ('GN', 'jongno'), ('EP', 'eunpyeong'), ('J', 'jung'), ('YS', 'yongsan'), ('SB', 'seongbuk'), ('GB', 'gangbuk'), ('DB', 'dobong'), ('NW', 'nowon'), ('DDM', 'dongdaemun'), ('SD', 'seongdong'), ('JN', 'jungnang'), ('GJ', 'gwangjin')], max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
                ('like_count', models.IntegerField(default=0)),
                ('title1', models.TextField()),
                ('description1', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title2', models.TextField()),
                ('description2', models.TextField()),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title3', models.TextField()),
                ('description3', models.TextField()),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('like_users', models.ManyToManyField(blank=True, related_name='check_notices', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
