# Generated by Django 4.1 on 2022-08-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(null=True, to='course.hashtag'),
        ),
    ]
