# Generated by Django 4.1 on 2022-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('MP', '마포구'), ('GS', '강서구'), ('YC', '양천구'), ('GR', '구로구'), ('YDP', '영등포구'), ('GC', '금천구'), ('DJ', '동작구'), ('GA', '관악구'), ('SC', '서초구'), ('GN', '강남구'), ('SP', '송파구'), ('GD', '강동구'), ('SDM', '서대문구'), ('GN', '종로구'), ('EP', '은평구'), ('J', '중구'), ('YS', '용산구'), ('SB', '성북구'), ('GB', '강북구'), ('DB', '도봉구'), ('NW', '노원구'), ('DDM', '동대문구'), ('SD', '성동구'), ('JN', '중랑구'), ('GJ', '광진구')], default='MP', max_length=50),
        ),
    ]
