# Generated by Django 4.1 on 2022-08-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_hashtag_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(to='course.hashtag'),
        ),
    ]
